### ISSUE TITLE
Create supabase db and connect from client

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#1]
1. Create the following db schema in supabase.
2. Add some sample data.
3. From the svelte app, connect to this db, fetch data and show as table.

```
Table "shops" with columns (
  id int8,
  name text,
  owner text,
  phone int8,
  address text,
  lat float8,
  lng float8
)

Table "orders" with columns (
  id int8,
  shop_id int8 foreign key references shops.id on delete cascade on update cascade,
  order_date timestampz,
  items text,
  delivery_date timestampz,
  delivered boolean
)
```

**Comment by gopal-vsg** [comment]
The tables in Supabase have been created as prescribed, and the data fetching and display is successfully completed.
![Screenshot 2024-07-17 210240](https://github.com/user-attachments/assets/23e3aa2f-a179-4c83-a037-ec8cdc589ddf)
