### ISSUE TITLE
Bind a popup to each marker with its shop details

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#11]
Bind popups to each marker with the shop details of that marker.
`marker.bindPopup("<b>Shop Name</b><br>Owner<br>Phone<br>Address")`

Verification: Click on a marker and see if a popup opens showing details.

Ref: https://leafletjs.com/examples/quick-start/

**Comment by gopal-vsg** [comment]
Marker popup feature added and deployed 
https://shopmap.vercel.app/
![image](https://github.com/user-attachments/assets/e22327b8-b69e-47ec-b35f-209af606c442)
