### ISSUE TITLE
Remove "place order" and introduce "create order" and "edit order" with the following options

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#13]
This is not a customer portal. Its for a distributor to keep track of goods distribution to various shops.
So instead of "place order", we need the following.

1. "Create Order" with fields - Shop (select), Items (textarea), Periodic (checkbox), Period (number field indicating number of days).
2. "Edit Order" allow editing of all above fields.

Note: Order has a field "latest delivery date" which is not editable here. It will be updated while marking an order as delivered.

**Comment by gopal-vsg** [comment]
Create order with Perodicity details is added

![image](https://github.com/user-attachments/assets/370c93e2-b0e8-4919-bb74-9be9a0458f62) ![image](https://github.com/user-attachments/assets/9c89adcf-7827-487b-9508-086a05a7089c)

edit order output screenshots are added in issue #14
