### ISSUE TITLE
Ability to mark order as delivered

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#14]
User should be able to mark an order as "delivered". Also we will ask user to input the delivery date which will be noted in "order.last_delivered_date" as date field.

**Comment by gopal-vsg** [comment]
when we click on any order in the order list, a pop will open and provide with options of edit, mark as delivered (which updates the last_delivered_date) and delete order options.
![image](https://github.com/user-attachments/assets/3fcf587e-cc1f-425a-aac3-35a1055f6b83)

The edit order page - where we can change all the parameters 
![image](https://github.com/user-attachments/assets/a8a0d146-c1c3-407f-a524-f314cbe906ef)
