### ISSUE TITLE
Change title to ShopMap instead of Vite + Svelte + TS and add favicon and logo

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#15]
1. Fix title in index.html.
2. Also use the attached image for favicon. Put it under public/logo.png and edit index.html to  `<link rel="icon" type="image/png" href="/logo.png" />`
![shopmap-logo](https://github.com/user-attachments/assets/6b03e16e-ff4a-4aa0-a9f2-f00febb66ab3)
3. Show this logo in the login page above the username,password input fields. (size 128x128)

**Comment by gopal-vsg** [comment]
I removed the background of the image sir, and tried to make it look better, but i think there is some styling  need to be done .
![image](https://github.com/user-attachments/assets/0c20dc04-80bd-4812-909b-d616160cad37)
and the code is deployed to vercel

**Comment by venuwiz** [comment]
Use this logo instead.

![logo-256](https://github.com/user-attachments/assets/4894c48d-feca-4c0a-9ba4-f47e3933885a)

**Comment by gopal-vsg** [comment]
Logo updated
