### ISSUE TITLE
Do not use getElementById. Use bind:this instead

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#16]
In svelte, we do not directly use DOM methods as much as possible.
So instead of get element by id, we bind the element to a variable and call showModal on that variable.

```
let orderDialog:HTMLDialogElement;

...
<dialog id="PlaceOrder" bind:this={orderDialog}></dialog>

...
<button on:click={()=>{ orderDialog.showModal() }>Create order</button>
```

https://github.com/gopal-vsg/shopmap/blob/db43049bba26fb6d0bd75dff4824d097cd5cf674/src/App.svelte#L60

**Comment by gopal-vsg** [comment]
Updated the code to use bind:this instead of DOM methods👍
