### ISSUE TITLE
Dialog IDs are named wrongly. Please fix it.

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#17]
Dialog ID with PlaceOrder is containing CreateShop element. Same for the other dialog also.
Please fix the IDs

https://github.com/gopal-vsg/shopmap/blob/db43049bba26fb6d0bd75dff4824d097cd5cf674/src/App.svelte#L110

**Comment by gopal-vsg** [comment]
corrected the naming of components and elements
