### ISSUE TITLE
Lets move the table to the left hand side of map

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#18]
I tried playing with the UI.
Scrolling up and down between map and table is hard.
So lets move the table to left hand panel like Google maps as shown in the images.

You can use
```
<div class="flex flex-row gap-1">
   <div>... left hand panel </div>
   <LeafLet />
</div>
```

With this functionality.
1. On clicking an item in the left hand panel (LHP), map will pan to that location and show popup.
2. Clicking the detail button will open up a modal with full shop details.
3. Same for orders. Show the orders as a list in LHP. Pan to the corresponding shop when an order is clicked.
4. On clicking detail button, show the order modal.

To show the detail button, you can use justify-between
```
<div class="flex flex-row justify-between">
  <span class="text-bold ... ">title</span>
  <button>Detail</button>
</div>
```

![4](https://github.com/user-attachments/assets/c90e3648-213f-41da-99e8-76470db55d03)
![5](https://github.com/user-attachments/assets/0861bb31-5772-407c-bfcb-26e40b82a705)

**Comment by venuwiz** [comment]
I just found a website with free svg icons. You can use it for the project. Hover on any icon and click on "Copy SVG" and use anywhere in our code.

https://heroicons.com/

**Comment by gopal-vsg** [comment]
Sir, 
I have completed the layout changes and incorporated interactive buttons into the application. However, I have not yet addressed responsiveness for mobile devices.

Could you please confirm whether the application is intended to be used on mobile devices as well? If so, I will make the necessary adjustments to ensure proper responsiveness.

![WhatsApp Image 2024-08-15 at 15 28 03_45eeb7c9](https://github.com/user-attachments/assets/245fef40-6a21-4ddd-92e9-88cb0c039083)
![WhatsApp Image 2024-08-15 at 15 28 03_d534544f](https://github.com/user-attachments/assets/e6fa1078-1219-4733-b73a-73dc2c027870)
![WhatsApp Image 2024-08-15 at 15 28 04_082d8483](https://github.com/user-attachments/assets/5b7aa583-fe5a-416b-a78a-b229c7e9331c)

**Comment by venuwiz** [comment]
No need to design for mobile interface. Its web-only for now. We can take care of mobile responsiveness later if required.

**Comment by venuwiz** [comment]
By the way, the redesigned UI looks great. Thanks for doing it.
