### ISSUE TITLE
Add leaflet js to this project

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#2]
1. Add leaflet js to this project
  a. https://leafletjs.com/examples/quick-start/
2. Only add a marker. No need for circle and polygon.
3. Show one marker per shop in the shops db using lat,lng columns of the shop.

**Comment by venuwiz** [comment]
This is the mock of the app. App UI should look like this approximately.

![shopmap-mock](https://github.com/user-attachments/assets/8f6801a0-99d0-47ff-af0b-8f703b3faa40)

**Comment by gopal-vsg** [comment]
Leaflet added to the page with markers locating the addresses of Shops and UI is improved.
![screencapture-localhost-5173-2024-07-18-17_25_02](https://github.com/user-attachments/assets/2b5af3f8-0c95-4c18-aaa0-8fde9af82bd3)
