### ISSUE TITLE
Replace shops table with "retailers"

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#20]
Create new retailers table with the same fields as shops and then delete shops table.
Also add the corresponding wholesaler_id
Then use retailers table wherever shops table was referenced.

create table retailers with fields
 - all fields same as shops table
 - wholesaler_id - pointing to wholesalers.id (who is the supplier of this retailer)

**Comment by gopal-vsg** [comment]
Whole Saler ID is Created, and Used the Term "Retailer" instead of Shop

Note : The file names are still Using the Term "Shop", Will update that Soon
