### ISSUE TITLE
Add location by getting current location of the mobile

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#24]
Instead of going to maps and copying lat-lng, give an option to detect the current location of the device and fill the lat lng using that.

[GeoLocation API for Web](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)

**Comment by gopal-vsg** [comment]
The coordinates are automatically being added (upto 4 place decimal accuracy) - these is still an option for the user to add the coordinates manually 
![{19ED6DD7-360C-438D-A37A-0E494EDC6307}](https://github.com/user-attachments/assets/8a56f23e-2933-4527-bd36-7cee1ce37516)
