### ISSUE TITLE
Add notes to retailer info

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#25]
Allow user to takes notes while creating/updating retailer info. Along with filling name, address etc., the user should be able to take text notes or upload audio clip as notes.

This is to store extra information about the retailer.

**Comment by gopal-vsg** [comment]
![{BABB79D4-36FE-4C84-9F38-F6952C3AC870}](https://github.com/user-attachments/assets/4f556c93-5f87-4e48-bde7-d7def2b2cd71)
Voice notes and notes feature added

**Comment by gopal-vsg** [comment]
Notes regarding the retailer are  being added to the database

![{8E9FECC9-8CFC-451C-ABFA-04418B71F512}](https://github.com/user-attachments/assets/103384c8-e388-482a-a744-b0e50ab125f0)
