### ISSUE TITLE
While marking as delivered - allow to edit delivery date

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#26]
Allow user to edit the delivery date before marking as delivered.

Remove the "Mark as Delivered" button and design the UI flow like this.
1. In the order details UI, show the order as "Pending".
2. The user can change the Pending status to "Delivered".
3. When they change to delivered, show the delivery date as current date and also make it editable.
4. Then user clicks "Confirm" to save the change.

**Comment by gopal-vsg** [comment]
I’ve updated the order details UI as requested:

Orders now display as "Pending" by default.
Users can switch the status to "Delivered," which sets the delivery date to the current date, making it editable.
The "Mark as Delivered" button has been removed, and users can simply click "Confirm" after adjusting the date to save all changes.
![{AF1DB10B-4C28-4DDB-A202-0E9AEB3CB237}](https://github.com/user-attachments/assets/30537b62-92ed-46f3-9682-11ecb6f98ad9) 
![{D3ED777E-0AD7-4995-9122-2974BAF9D176}](https://github.com/user-attachments/assets/6850cb4c-3c85-486f-945b-8d2a77c45b0e)
