### ISSUE TITLE
Remove periodic order and make order creation on demand

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#28]
1. Remove the periodic option from the order.
2. Create Order form should show the current fields (without the periodic option) and also show the last ordered date.

**Comment by gopal-vsg** [comment]
Periodic fucntion removed 
![{173A474C-7DCB-47B0-B101-E7EAD10655E3}](https://github.com/user-attachments/assets/8e6139de-6693-471c-a306-3ecb1907ad86)
