### ISSUE TITLE
Commit the supabase schema to a sql file in this repo

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#3]
We need to dump the supabase schema into a sql file so that we can recreate the db later if its lost, without the need for manually creating all tables again.

Steps to dump
1. Install postgres-client
  a. `sudo apt install postgresql-client`
2. Goto your supabase.com project >> Left hand panel >> Project settings >> Database (under Configuration section) >> Connection string >> PSQL.
3. You will see a command like
  a. `psql -h something.pooler.supabase.com -p 6543 -d postgres -U postgres.yourprojectid`
4. Remove psql and use pg_dump like this
  a. `pg_dump -h something.pooler.supabase.com -p 6543 -d postgres -U postgres.yourprojectid -s public  --clean --schema-only > supabase_schema.sql`
5. Remove the config statements at the top of supabase_schema.sql. They will look like
```
set something 100
set anotherval 200
```
6. Commit the sql file to shopmap/backend/supabase_schema.sql. Please don't put it under src/ because this is not svelte code.

Whenever you modify the schema in supabase UI, dump again and commit to this repo.

**Comment by gopal-vsg** [comment]
Schema file added to the backend folder,
These are the set configuration statements I removed as per your instructions. Please let me know if I accidentally deleted something important so I can add it back.
```

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
```
