### ISSUE TITLE
Please use pnpm instead of npm

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#5]
Please use "pnpm install" and "pnpm run dev" etc. instead of "npm".
Delete package-lock.json which is created by npm and use only pnpm-lock.yaml which is created by pnpm.

https://github.com/gopal-vsg/shopmap/blob/a84746e55a1125c34a6789971c5f65ae5fcecdd6/package-lock.json#L2

**Comment by gopal-vsg** [comment]
will be using pnpm from now on sir.👍
