### ISSUE TITLE
Protect supabase db with your user id

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#6]
A) Create your user in supabase db
1. Goto supabase >> Authentication
2. Goto Providers >> Email >> Enable Email Provider
3. Goto Users >> Add user button >> Create new user
4. Enter your email id, some password and enable auto-confirm-user. This password will be used to login to shopmap web application.

B) Disable new user sign ups.
1. Supabase >> Project Settings >> Authentication >> Disable "Allow new users to signup".
2. This will only disable signups through the webapp. We can still add users through supabase >> Authentication.

C) Setup row level security in db
Goto supabase >> Database >> Policies
1. For each table in the database
2. Enable RLS
3. Create a policy with name "Only authenticated users can access the table" on the table for "all" actions to "authenticated" role. The final policy will look like:
```
create policy "Only authenticated users can access the table"
  on "public"."table_name"
  as PERMISSIVE
  for ALL
  to authenticated
  using (true);
```

**Comment by gopal-vsg** [comment]
I enabled email authentication, created a new user, and ensured the auto-confirm-user option is active. I also disabled new user sign-ups to restrict access. Row Level Security (RLS) is enabled for each table, with a policy allowing only authenticated users to access the tables.
![Screenshot 2024-07-23 123421](https://github.com/user-attachments/assets/f40dbaa5-f1a2-4997-abb3-d6d13bed03c6)
