### ISSUE TITLE
Introduce login logout in web ui

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#7]
Create a login dialog asking for email id, password. Once users enters info and clicks Login button, you can login using a function like the one below.

```
async function signInWithEmail() {
  const { data, error } = await supabase.auth.signInWithPassword({
    email: 'example@email.com',
    password: 'example-password',
  })
}
```
[Reference](https://supabase.com/docs/guides/auth/passwords?queryGroups=language&language=js#signing-in-with-an-email-and-password)

After logging in, goto the home page.
Introduce a Logout button in the top right corner of the screen which will invoke
```
async function signOut() {
  const { error } = await supabase.auth.signOut()
}
```

NOTE: In the home page onMount(), invoke supabase.auth.getUser() and check if it returns user. If user is present, show the home page, otherwise show the login dialog.
[Reference](https://supabase.com/docs/reference/javascript/auth-getuser)

**Comment by gopal-vsg** [comment]
Login and Logout feature is added 
![image](https://github.com/user-attachments/assets/28217f27-d387-4382-b126-a61c8c6616e3)
![image](https://github.com/user-attachments/assets/9fabd848-c4d5-4d07-a934-9e49df38852e)
